group "examples"

dependencies {
    implementation "org.springframework.boot:spring-boot-starter-logging"
    implementation "org.springframework.boot:spring-boot-autoconfigure"
    implementation "org.apache.grails:grails-core"
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-tomcat"
    implementation ("org.apache.grails:grails-dependencies") {
        exclude module:'grails-datastore-simple'
    }
    implementation "org.apache.grails:grails-codecs"
    implementation "org.apache.grails:grails-services"
    implementation "org.apache.grails:grails-datasource"
    implementation "org.apache.grails.web:grails-web-boot"
    implementation "org.apache.grails:grails-logging"
    implementation "org.apache.grails:graills-cache"
    implementation "org.apache.grails:grails-events"
    implementation project(":grails-plugin")
    implementation "org.apache.grails:grails-views-gson"
    implementation "org.apache.grails:grails-data-mongodb-gson-templates"
    implementation 'org.apache.grails:grails-spring-security-rest:3.0.1'
    profile "org.grails.profiles:rest-api"
    testImplementation project(':grails-testing-support-datamapping')
    testImplementation "org.apache.grails:grails-testing-support-web:$testingSupportVersion"
    testRuntimeOnly "org.neo4j.test:neo4j-harness:$neo4jVersion"
}
