plugins {
    id 'org.apache.grails.gradle.grails-web'
}

version = projectVersion
group = 'examples'

configurations {
    astTransformation
}

dependencies {
    implementation platform("org.apache.grails:grails-bom:$grailsVersion")
    //astTransformation platform("org.apache.grails:grails-bom:$grailsVersion")

    astTransformation 'jakarta.servlet:jakarta.servlet-api'
    astTransformation 'org.apache.grails:grails-controllers'

    implementation project(':hibernate5-grails-plugin')
    implementation 'org.apache.grails:grails-core'
    implementation 'org.apache.grails:grails-domain-class'

    runtimeOnly 'com.h2database:h2'
    runtimeOnly 'com.zaxxer:HikariCP'
    runtimeOnly 'org.apache.grails:grails-databinding'
    runtimeOnly 'org.apache.grails:grails-controllers'
    runtimeOnly 'org.springframework.boot:spring-boot-autoconfigure'
    runtimeOnly 'org.springframework.boot:spring-boot-starter-logging'
    runtimeOnly 'org.springframework.boot:spring-boot-starter-tomcat'

    testImplementation 'org.apache.grails.testing:grails-testing-support-core'

    testRuntimeOnly "org.apache.grails:grails-testing-support-web"
}

sourceSets {
    main {
        compileClasspath += configurations.astTransformation
    }
    integrationTest {
        compileClasspath += configurations.astTransformation
    }
}

apply {
    from rootProject.layout.projectDirectory.file('gradle/java-config.gradle')
    from rootProject.layout.projectDirectory.file('gradle/hibernate5-test-config.gradle')
    from rootProject.layout.projectDirectory.file('gradle/example-config.gradle')
}