plugins {
    id 'org.apache.grails.gradle.grails-web'
    id 'org.apache.grails.gradle.grails-gsp'
    id 'com.bertramlabs.asset-pipeline'
}

version = projectVersion
group = 'examples'

dependencies {
    implementation platform("org.apache.grails:grails-bom:$grailsVersion")
    integrationTestImplementation platform("org.apache.grails:grails-bom:$grailsVersion")

    implementation project(':hibernate5-grails-plugin')
    implementation 'jakarta.persistence:jakarta.persistence-api'
    implementation 'jakarta.validation:jakarta.validation-api'
    implementation 'org.apache.grails:grails-core'
    implementation 'org.apache.grails:grails-rest-transforms'
    implementation 'org.apache.grails:grails-gsp'

    runtimeOnly 'com.bertramlabs.plugins:asset-pipeline-grails'
    runtimeOnly 'com.h2database:h2'
    runtimeOnly 'com.zaxxer:HikariCP'
    runtimeOnly 'org.apache.grails:grails-databinding'
    runtimeOnly 'org.apache.grails:grails-i18n'
    runtimeOnly 'org.apache.grails:grails-services'
    runtimeOnly 'org.apache.grails:grails-url-mappings'
    runtimeOnly 'org.apache.grails:grails-fields'
    runtimeOnly "org.hibernate:hibernate-ehcache:$hibernateVersion", {
        // exclude javax variant of hibernate-core 5.6
        exclude group: 'org.hibernate', module: 'hibernate-core'
    }
    runtimeOnly "org.jboss.spec.javax.transaction:jboss-transaction-api_1.3_spec:$jbossTransactionApiVersion", {
        // required for hibernate-ehcache to work with javax variant of hibernate-core excluded
    }
    runtimeOnly 'org.springframework.boot:spring-boot-autoconfigure'
    runtimeOnly 'org.springframework.boot:spring-boot-starter-logging'
    runtimeOnly 'org.springframework.boot:spring-boot-starter-tomcat'

    testImplementation 'org.apache.grails.testing:grails-testing-support-core'
    testImplementation "org.apache.grails:grails-testing-support-web"

    integrationTestImplementation testFixtures('org.apache.grails:grails-geb')
}

apply {
    from rootProject.layout.projectDirectory.file('gradle/java-config.gradle')
    from rootProject.layout.projectDirectory.file('gradle/hibernate5-test-config.gradle')
    from rootProject.layout.projectDirectory.file('gradle/example-config.gradle')
}