version = projectVersion
group = 'examples'

apply plugin: 'groovy'
apply plugin: 'org.apache.grails.gradle.grails-web'

dependencies {

    implementation platform("org.apache.grails:grails-bom:$grailsVersion")
    integrationTestImplementation platform("org.apache.grails:grails-bom:$grailsVersion")

    implementation project(':mongodb-grails-plugin')
    implementation 'org.apache.grails:grails-core'
    implementation 'org.apache.grails:grails-rest-transforms'
    implementation 'org.apache.grails.web:grails-web-boot'
    implementation 'org.apache.grails:grails-gsp'
    implementation project(':hibernate5-grails-plugin')

    runtimeOnly 'com.bertramlabs.plugins:asset-pipeline-grails'
    runtimeOnly 'com.h2database:h2'
    runtimeOnly 'com.zaxxer:HikariCP'
    runtimeOnly 'org.fusesource.jansi:jansi'
    runtimeOnly 'org.apache.grails:grails-scaffolding'
    runtimeOnly 'org.apache.grails:grails-i18n'
    runtimeOnly 'org.apache.grails:grails-url-mappings'
    runtimeOnly "org.hibernate:hibernate-ehcache:$hibernateVersion", {
        // exclude javax variant of hibernate-core
        exclude group: "org.hibernate", module: "hibernate-core"
    }
    runtimeOnly "org.jboss.spec.javax.transaction:jboss-transaction-api_1.3_spec:$jbossTransactionApiVersion", {
        // required for hibernate-ehcache to work with javax variant of hibernate-core excluded
    }
    runtimeOnly 'org.springframework.boot:spring-boot-autoconfigure'
    runtimeOnly 'org.springframework.boot:spring-boot-starter-logging'
    runtimeOnly 'org.springframework.boot:spring-boot-starter-tomcat'

    testImplementation testFixtures(project(':mongodb-grails-plugin'))
    testImplementation 'org.apache.grails.testing:grails-testing-support-core'
    testImplementation 'org.spockframework:spock-core'
    testImplementation "org.testcontainers:mongodb:$testcontainersMongodbVersion"

    integrationTestImplementation testFixtures('org.apache.grails:grails-geb')
}

apply from: rootProject.layout.projectDirectory.file('gradle/java-config.gradle')
apply from: rootProject.layout.projectDirectory.file('gradle/mongodb-test-config.gradle')