version = projectVersion
group = 'examples'

apply plugin: 'groovy'
apply plugin: 'org.apache.grails.gradle.grails-web'

dependencies {
    implementation platform("org.apache.grails:grails-bom:$grailsVersion")

    implementation 'org.apache.grails:grails-core'
    implementation 'org.apache.grails.web:grails-web-boot'
    implementation 'org.apache.grails:grails-views-gson'
    implementation 'org.apache.grails:grails-mimetypes'
    implementation 'org.apache.grails.web:grails-web-url-mappings'
    implementation 'org.apache.grails:grails-views-markup'
    implementation 'org.apache.grails:grails-gsp'
    implementation 'org.apache.grails:grails-databinding'
    implementation 'org.apache.grails:grails-rest-transforms'
    implementation 'org.apache.grails:grails-url-mappings'
    implementation project(':mongodb-core')

    runtimeOnly 'org.springframework.boot:spring-boot-autoconfigure'
    runtimeOnly 'org.springframework.boot:spring-boot-starter-logging'
    runtimeOnly 'org.springframework.boot:spring-boot-starter-tomcat'

    runtimeOnly project(':mongodb-gson-templates')
    runtimeOnly 'com.bertramlabs.plugins:asset-pipeline-grails'

    integrationTestImplementation 'org.apache.grails.testing:grails-testing-support-core'
}

apply from: rootProject.layout.projectDirectory.file('gradle/java-config.gradle')
apply from: rootProject.layout.projectDirectory.file('gradle/mongodb-test-config.gradle')
