package org.grails.datastore.mapping.model;

/**
 * Value generation strategies
 *
 * @author Graeme Rocher
 * @since 6.0
 */
public enum ValueGenerator {
    /**
     * Generated natively from the underlying datastore
     */
    NATIVE,
    /**
     * Generated through assignment
     */
    ASSIGNED,
    /**
     * Generated by the datastore implementation
     */
    GENERATED,
    /**
     * The default generated
     */
    AUTO,
    /**
     * Generated from a sequence
     */
    SEQUENCE,
    /**
     * A generator that uses a HILO algorithm
     */
    HILO,
    /**
     * A generator that uses an auto-increment column
     */
    INCREMENT,
    /**
     * A generator that uses UUIDs
     */
    UUID,
    /**
     * A generator that uses UUID2s
     */
    UUID2

}
