assetPipelineVersion=3.3.4
cglibNodepVersion=3.3.0
datastoreVersion=8.0.4
gebVersion=2.3
gparsVersion=1.2.1
grailsVersion=6.0.0
grailsGradlePluginVersion=6.1.2
groovyVersion=3.0.20
h2Version=1.4.200
hibernateDatastoreVersion=8.0.2
hibernateEhcacheVersion=5.5.7.Final
hibernateValidatorVersion=6.2.5.Final
jansiVersion=2.4.1
javaParserCoreVersion=3.25.8
javassistVersion=3.30.2-GA
jettyVersion=9.4.29.v20200521
junitJupiterVersion=5.10.2
junitPlatformVersion=1.10.2
neo4jDriverVersion=4.4.13
neo4jVersion=3.5.35
objenesisVersion=3.2
picocliVersion=4.7.1
pluginGrailsVersion=6.1.2
projectVersion=8.1.0-SNAPSHOT
seleniumSafariDriverVersion=3.14.0
seleniumVersion=3.14.0
servletApiVersion=4.0.1
spockVersion=2.1-groovy-3.0
springBootVersion=2.7.18
springVersion=5.3.39

org.gradle.caching=true
org.gradle.daemon=true
#org.gradle.parallel=true
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx1536M -XX:MaxMetaspaceSize=512M
