dependencies {
    implementation "org.springframework.boot:spring-boot-starter-logging"
    implementation "org.springframework.boot:spring-boot-autoconfigure"
    implementation "org.apache.grails:grails-core"
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-tomcat"
    implementation "org.apache.grails:grails-url-mappings"
    implementation "org.apache.grails:grails-rest-transforms"
    implementation "org.apache.grails:grails-codecs"
    implementation "org.apache.grails:grails-interceptors"
    implementation "org.apache.grails:grails-services"
    implementation "org.apache.grails:grails-datasource"
    implementation "org.apache.grails:grails-databinding"
    implementation "org.apache.grails.web:grails-web-boot"
    implementation "org.apache.grails:grails-logging"
    implementation "org.apache.grails:grails-cache"
    implementation "org.apache.grails:grails-async"
    implementation "org.apache.grails:grails-events"
    implementation "org.apache.grails:grails-data-hibernate5"
    implementation "org.hibernate:hibernate-core:$hibernateCoreVersion"
    implementation "org.apache.grails:grails-views-gson"
    implementation "org.apache.grails:grails-data-mongodb-gson-templates"
    implementation 'io.micronaut.rxjava2:micronaut-rxjava2-http-client:1.2.0'
    console "org.apache.grails:grails-console"
    profile "org.grails.profiles:rest-api"
    runtimeOnly "org.glassfish.web:el-impl:2.1.2-b03"
    runtimeOnly "com.h2database:h2"
    runtimeOnly "org.apache.tomcat:tomcat-jdbc"
    testImplementation project(':grails-testing-support-datamapping')
    testImplementation "org.apache.grails:grails-testing-support-web"

    implementation project(":grails-plugin-gorm-graphql-plugin")
}

bootRun {
    jvmArgs('-Dspring.output.ansi.enabled=always')
    sourceResources sourceSets.main
}
tasks.withType(Test) {
    useJUnitPlatform()
}