name: Maven Central Sync
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (eg: 1.2.3)'
        required: true
jobs:
  central-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: v${{ github.event.inputs.release_version }}
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
      - name: Syncs with Maven Central/Sonatype
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        run: |
          ./gradlew synchronizeWithMavenCentral --no-daemon
